### ISSUE TITLE
Overwriting fil files in Writer

### ISSUE THREAD

**Issue by KshitijAggarwal** [devanshkv/your#19]
`to_fil` in `Writer` currently overwrites the fil file, if a file with outname is already present. This can lead to a lot of confusion. A solution for this would be useful. Could either be a warning/Error or a bit different way to write fil files.

**Comment by devanshkv** [comment]
Warn and overwrite!

**Comment by KshitijAggarwal** [comment]
added a warning with https://github.com/devanshkv/your/commit/4a64e40bcd0951f2eb57d6ba070e86e430cb0a7c
