### ISSUE TITLE
Fix Candidate tests

### ISSUE THREAD

**Issue by KshitijAggarwal** [devanshkv/your#26]
Candidate tests seem to be failing, maybe because of low tolerance in the comparison. 
Need to fix that.

**Comment by KshitijAggarwal** [comment]
It is also giving a TypeError: https://github.com/devanshkv/your/runs/1005097401

**Comment by devanshkv** [comment]
Yes because for some reason `dispersion_delay` is `None`.

**Comment by KshitijAggarwal** [comment]
:(

**Comment by devanshkv** [comment]
0eeda390d4f6270f1afd6a618d54dbb412ddee86 fixed it.
